#!/usr/bin/env python3

from atof import atof
import numpy as np
import matplotlib.pyplot as plt

def load_data(path: str) -> dict:
    with open(path) as file:
        return np.array([
            list(map(atof, line.split()))
            for line in file
        ])

x = np.array([[1., 1., 1., 1.]])
data = {
    k: load_data(f'solve-{k}.out')
    for k in ('gd', 'cg')
}
for label, value in data.items():
    print(label, end=':\n')
    print(value)
print(end='', flush=True)

for label, value in data.items():
    for yscale in 'linear', 'log':
        plt.title('processes of two iterative methods')
        plt.xlabel('iterations')
        plt.ylabel('norm-2 error')
        plt.yscale(yscale)
        plt.plot(range(1, 1 + len(value)), np.linalg.norm(value - x, 2, 1), label=label)
        plt.legend()
        plt.savefig(f'{label}-{yscale}.pdf')
        plt.show()
