#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

with open('stat.out') as f:
    data = np.array([int(l) for l in f])
print(data)

plt.title('iteration times per run')
plt.xlabel('times')
plt.ylabel('runs')
plt.hist(data, 20, (280, 400))
plt.savefig('vibra.pdf')
plt.show()
